[tool.black]
color = true
line-length = 120
target-version = ['py312']
skip-string-normalization = true
exclude="""
(
  migrations
  | .git
  | __pycache__
)
"""
[tool.isort]
profile = "black"
py_version = 311
line_length = 120
known_first_party = 'pydantic_settings'
known_third_party = ['pydantic']
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
skip="migrations"