# Generated by Django 5.1.4 on 2024-12-08 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CustomerEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('username', models.CharField(blank=True, max_length=80, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seas_customer',
            },
        ),
    ]
