# Generated by Django 5.1.4 on 2024-12-08 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sessionentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('last_update_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=80)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('start_selling_time', models.DateTimeField(db_index=True)),
                ('end_selling_time', models.DateTimeField(db_index=True)),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('OPEN', 'Open'),
                            ('CLOSED', 'Closed'),
                            ('CANCELLED', 'Cancelled'),
                            ('COMPLETED', 'Completed'),
                        ],
                        db_index=True,
                        max_length=9,
                    ),
                ),
            ],
            options={
                'db_table': 'seas_match',
            },
        ),
        migrations.CreateModel(
            name='SeatEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('last_update_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'seas_seat',
            },
        ),
        migrations.CreateModel(
            name='StadiumEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('last_update_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'seas_stadium',
            },
        ),
        migrations.CreateModel(
            name='SeatPriceEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('last_update_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.matchentity')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.seatentity')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.stadiumentity')),
            ],
            options={
                'db_table': 'seas_seat_price',
            },
        ),
        migrations.AddField(
            model_name='seatentity',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.stadiumentity'),
        ),
        migrations.AddField(
            model_name='matchentity',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.stadiumentity'),
        ),
        migrations.AddConstraint(
            model_name='matchentity',
            constraint=models.CheckConstraint(
                condition=models.Q(('state__in', ['OPEN', 'CLOSED', 'CANCELLED', 'COMPLETED'])),
                name='app_matchentity_state_valid',
            ),
        ),
    ]
