# Generated by Django 5.1.4 on 2024-12-09 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_matchentity_seatentity_stadiumentity_seatpriceentity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMatchSeatEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('last_update_time', models.DateTimeField(auto_now=True, db_index=True)),
                (
                    'state',
                    models.CharField(choices=[('RESERVED', 'Reserved'), ('SOLD', 'Sold')], db_index=True, max_length=8),
                ),
                (
                    'customer',
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.customerentity'),
                ),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.matchentity')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.seatentity')),
            ],
            options={
                'db_table': 'seas_customer_match_seat',
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('state__in', ['RESERVED', 'SOLD'])),
                        name='app_customermatchseatentity_state_valid',
                    )
                ],
            },
        ),
    ]
