# Generated by Django 5.1.4 on 2024-12-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_depositentity_invoiceentity_invoiceitementity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customermatchseatentity',
            name='app_customermatchseatentity_state_valid',
        ),
        migrations.AlterField(
            model_name='customermatchseatentity',
            name='state',
            field=models.CharField(
                choices=[('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('CANCELED', 'Canceled')],
                db_index=True,
                default='RESERVED',
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name='customermatchseatentity',
            constraint=models.CheckConstraint(
                condition=models.Q(('state__in', ['RESERVED', 'SOLD', 'CANCELED'])),
                name='app_customermatchseatentity_state_valid',
            ),
        ),
    ]
